name: Run Cukinia Tests

on: [push]

jobs:
    test-cukinia:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                submodules: true
            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y wget iproute2 bats bats-assert shellcheck libxml2-utils
            # TODO fix shellcheck errors
            - name: Lint code
              run: shellcheck -e SC1090,SC2027,SC2034,SC2046,SC2059,SC2060,SC2086,SC2124,SC2155,SC2188,SC3043,SC1091,SC2143,SC2026 ./cukinia
            - name: Run Cukinia Tests
              run: bats bats/cukinia.bats
